apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: testapp-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: testapp
  endpoints:
  - port: web
    path: /metrics
